project:
  type: website
  output-dir: docs


website:
  page-navigation: true
  title: "R Workshops for data Science"
  site-url: " https://aubreympungose.github.io/data_science_course/"

  repo-url:  https://aubreympungose.github.io/data_science_course/
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Aubrey Mpungose, 2022"
    
  sidebar:
    style: "docked"
    search: true
    collapse-level: 0
    contents:
      - section: "**Welcome**"
        contents:
          - index.qmd
          - my-profile.qmd
          - getting-started.qmd
          - schedule.qmd
          
      - section: "**Weekly materials**"
        contents:
          - href: weeks/week-1a.qmd
            text: "Week 1: Introduction: Basics of R functions"
          - href: weeks/week-1b.qmd
            text: "Week 1: Data Structures and Types"
          - href: weeks/week-2.qmd
            text: "Week 2: Data Visualisation"
          - href: weeks/week-3.qmd
            text: "Week 3: Data Manipulation"
          - href: weeks/week-4.qmd
            text: "Week 4: Exploratory Data Analysis, summary statistics"
          - href: weeks/week-5a.qmd
            text: "Week 5: ommunicating and Reporting Data"
          - href: weeks/week-5b.qmd
            text: "Week 5: Data Science Toolbox, where to from here?"

 
format:
 html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    
filters:
  - include-files.lua
  - quarto
        
execute:
  freeze: auto      