---
title: "Schedule"
---

| Week                    | Topic                                            | Presenter | Read                                                          |
|--------------|-------------------|--------------|--------------------------|-----------|---------------------------------------------------------------|
| [1](/weeks/week-1.html) | Introduction: Basics of R functions              | Aubrey    | [📖](/weeks/week-1.html#prepare){aria-label="Week 1 summary"} |
| [2](/weeks/week-2.html) | Data Structures and Types                        | Aubrey    | [📖](/weeks/week-2.html#prepare){aria-label="Week 2 summary"} |
| [3](/weeks/week-3.html) | Data Wrangling                                   | Aubrey    | [📖](/weeks/week-3.html#prepare){aria-label="Week 3 summary"} |
| [4](/weeks/week-4.html) | Data Visualisation                               | Aubrey    | [📖](/weeks/week-4.html#prepare){aria-label="Week 4 summary"} |
| [5](/weeks/week-5.html) | Exploratory Data Analysis, summary statistics    | Aubrey    | [📖](/weeks/week-5.html#prepare){aria-label="Week 5 summary"} |
| [6](/weeks/week-6.html) | Hypothesis Testing                               | Aubrey    | [📖](/weeks/week-6.html#prepare){aria-label="Week 6 summary"} |
| [7](/weeks/week-7.html) | Regression: Linear and Logistic                  | Aubrey    | [📖](/weeks/week-7.html#prepare){aria-label="Week 7 summary"} |
| [8](/weeks/week-8.html) | Communicating and Reporting Data using RMarkdown | Aubrey    | [📖](/weeks/week-8.html#prepare){aria-label="Week 8 summary"} |
| [8](/weeks/week-8.html) | Data Science Toolbox, where to from here?        | Aubrey    | [📖](/weeks/week-8.html#prepare){aria-label="Week 8 summary"} |                          |
